# Generated by Django 4.2.15 on 2024-10-22 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_player_slug_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='external_player_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='championships_won',
        ),
        migrations.RemoveField(
            model_name='team',
            name='external_team_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.DecimalField(decimal_places=2, default=160.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(default='Tanzanian', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
