# Generated by Django 4.2.15 on 2024-10-22 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_player_birthdate_and_more'),
        ('gameweeks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='referee',
        ),
        migrations.CreateModel(
            name='YellowCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField(help_text='Time in minutes when the yellow card was shown')),
                ('match_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yellow_cards', to='gameweeks.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yellow_cards', to='teams.player')),
            ],
        ),
        migrations.CreateModel(
            name='Tackle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successful', models.BooleanField(default=False)),
                ('time', models.PositiveIntegerField(help_text='Time in minutes when the tackle was made')),
                ('match_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tackles', to='gameweeks.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tackles', to='teams.player')),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField(help_text='Time in minutes when the substitution occurred')),
                ('match_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='gameweeks.fixture')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_in', to='teams.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_out', to='teams.player')),
            ],
        ),
        migrations.CreateModel(
            name='Shoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField(help_text='Time in minutes when the shot was taken')),
                ('result', models.CharField(choices=[('on_target', 'On Target'), ('off_target', 'Off Target'), ('blocked', 'Blocked')], max_length=20)),
                ('match_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoots', to='gameweeks.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoots', to='teams.player')),
            ],
        ),
        migrations.CreateModel(
            name='RedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField(help_text='Time in minutes when the red card was shown')),
                ('match_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_cards', to='gameweeks.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_cards', to='teams.player')),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('time', models.PositiveIntegerField(help_text='Time in minutes when the pass was made')),
                ('match_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='gameweeks.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='teams.player')),
            ],
        ),
        migrations.CreateModel(
            name='MatchStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_shots', models.PositiveIntegerField(default=0)),
                ('away_team_shots', models.PositiveIntegerField(default=0)),
                ('home_team_possession', models.PositiveIntegerField(default=0)),
                ('away_team_possession', models.PositiveIntegerField(default=0)),
                ('home_team_corners', models.PositiveIntegerField(default=0)),
                ('away_team_corners', models.PositiveIntegerField(default=0)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gameweeks.fixture')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scored_at', models.PositiveIntegerField(help_text='Time in minutes when the goal was scored')),
                ('goals_scored', models.PositiveIntegerField(default=1)),
                ('match_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='gameweeks.fixture')),
                ('scored_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='teams.player')),
            ],
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('won', 'Won'), ('lost', 'Lost')], max_length=10)),
                ('time', models.PositiveIntegerField(help_text='Time in minutes when the duel occurred')),
                ('match_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels', to='gameweeks.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels', to='teams.player')),
            ],
        ),
    ]
